# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['mcu_code_analyzer/main_gui.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('mcu_code_analyzer/config.yaml', '.'),
        ('mcu_code_analyzer/templates', 'templates'),
        ('mcu_code_analyzer/utils', 'utils'),
        ('mcu_code_analyzer/core', 'core'),
        ('mcu_code_analyzer/intelligence', 'intelligence'),
        ('mcu_code_analyzer/ui', 'ui'),
        ('mcu_code_analyzer/localization.py', '.'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'yaml',
        'requests',
        'chardet',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'base64',
        'zlib',
        'urllib.parse',
        'json',
        'pathlib',
        'subprocess',
        'threading',
        'queue',
        'datetime',
        'time',
        'os',
        'sys',
        'io',
        'logging',
        'configparser',
        'collections',
        'itertools',
        'functools',
        're',
        'math',
        'statistics',
        'hashlib',
        'uuid',
        'tempfile',
        'shutil',
        'glob',
        'fnmatch',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # 排除一些大型不必要的模块
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
        'jupyter',
        'IPython',
        'test',
        'tests',
        'unittest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='MCU_Code_Analyzer_v2.1.0',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,   # 启用strip减小文件大小
    upx=False,    # 暂时不用UPX避免问题
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None
)
